---
 name : chacks  

 on : [push]

 jobs : 
    test-lint: 
       name : Test and lint
       runs-on : ubentu-20.04
       steps :
       - name: Login to Docker Hub 
         uses: docker/login-action@v1
         with: 
         username: ${{secrets.DOCKERHUB_USER}}
         password: ${{secrets.DOCKERHUB_TOKEN}}
       - name: Checkout
         uses: actions/chackout@v2
       - name : lint
         run : docker-compose run --rm app sh -c "flake8"